include: fix sys/queue.h.
Currently there are a couple of public header files include
'sys/queue.h', which is a POSIX functionality.  When compiling DPDK
with OVS on Windows, we encountered issues such as, found the missing
header. In file included from ../lib/dpdk.c:27:
C:\temp\dpdk\include\rte_log.h:24:10: fatal error: 'sys/queue.h' file
not found

The patch fixes it by removing the #include <sys/queue.h> from
DPDK public headers, so programs including DPDK headers don't depend
on POSIX sys/queue.h. For Linux/FreeBSD, DPDK public headers only need a
handful of macros for list/tailq heads and links. Those macros should be
provided by DPDK, with RTE_ prefix. For Linux and FreeBSD it will just be:
    #include <sys/queue.h>
    #define RTE_TAILQ_ENTRY(type) TAILQ_ENTRY(type)
    /* ... */
For Windows, we copy these definitions from <sys/queue.h> to rte_os.h.
With this patch, all the public headers should not have
"#include <sys/queue.h>" or "TAILQ_xxx" macros.

Suggested-by: Nick Connolly <nick.connolly@mayadata.io>
Suggested-by: Dmitry Kozliuk <Dmitry.Kozliuk@gmail.com>
Signed-off-by: William Tu <u9012063@gmail.com>
---
v2->v3:
  * follow the suggestion by Dmitry
  * run checkpatches, there are some errors but I think either
    the original file has over 80-char line due to comments,
    or some false positive about macro.
v1->v2:
  - follow the suggestion by Nick and Dmitry
  - http://mails.dpdk.org/archives/dev/2021-August/216304.html

Signed-off-by: William Tu <u9012063@gmail.com>